
project_id = "your-project-id" # <- You need to replace this with your real project ID

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "extensions"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 15
max_client_conn = 100

[realtime]
enabled = true
ip_version = "IPV6"

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[auth.email]
enabled = true
double_confirm_changes = true
double_confirm_deletions = true

[analytics]
enabled = false
port = 54327

[experimental]
sso_enabled = false

[functions]
[functions.create-payment]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.chat-with-gemini]
verify_jwt = true
