// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypsvmwqrrrjnvmphoclx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlwc3Ztd3FycnJqbnZtcGhvY2x4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyODQ0OTEsImV4cCI6MjA2Mjg2MDQ5MX0.sFm_wT_8juH1OzPDS9D1Ti4D8tjiqpDVws1HpnTTXBY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);